### ISSUE TITLE
Website blocked

### ISSUE THREAD

**Issue by LugCentral** [3kh0/3kh0.github.io#68]
Brooo 3kh0 just got blocked from my school and i am sad but if you can fix it the extension used to block is
[http://lsrelay-config-production.s3.amazonaws.com/46be9bc67ec13b4fbf42a209c47e69250741157f6cb6b1e556f56be54801795b/block_screen.html?id=a7e6bf9e-b08f-430a-8831-9ac88f608331](THIS WEBSITE)
And i am incredibly bored and now more :( because of this. 
But I forked the repo and it is working fine so what do you think i should do?

**Comment by 3kh0** [comment]
Please use this link, https://3kh0-github-io.vercel.app/

**Comment by 3kh0** [comment]
Let me know if it works! :)

**Comment by Piplup7575** [comment]
lmao lightspeed is bad, every exploit I've found with them has been patched (probably because i reported a bunch of them last year, sue me)
Try opening the link from a trusted site, like from your school account through google docs, that worked for a while, 
or somehow just send 1000 requests in a sec because your computer is bad

**Comment by LugCentral** [comment]
Issue Resolved... I just Forked The Main Repo And Fetched Upstream and it works perfectly, thanks for yalls help with this issue!

**Comment by 3kh0** [comment]
@LugCentral make sure you just fetch upstream every so often to get updates!
