### ISSUE TITLE
[Bug] Make A repo for offline use with all assets

### ISSUE THREAD

**Issue by 0xkkl** [3kh0/3kh0.github.io#94]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Windows Laptop (or any device running Windows)

### Please explain the issue

If I have githack blocked then assets wont load since it loads from githack. My proposal is to make a github repo with all assets

**Comment by Russell2259** [comment]
There is already a repository with all the game assets but alas it is impossible and impractical to make a single an offline 3kh0 because 3kh0 requires multiple files and assets hosted on the internet, it uses certain functions that cannot be used on http of file origins and finally the total size of all the assets combined would be more than 5 gigabytes big.

The githack CDN is not the only CDN that is in use for 3kh0. You may be experiencing other disturbances try referring to issue #93 for a fix.

If the problem persists please reply.

**Comment by 3kh0** [comment]
We have 3 AWS CDNs also there to help with blocking

**Comment by Russell2259** [comment]
@0xkkl I also made a node.js CDN server you can host and configure with your fork of 3kho.github.io. The source code and deployment instructions can be found [here](https://github.com/Russell2259/3kh0-CDN).
